### ISSUE TITLE
Check Name

### ISSUE THREAD

**Issue by Marv93** [versus167/ini_xml#1]
Die check-name-Funktion ist nicht aggressiv genug. Es werden noch zu viele Sonderzeichen erlaubt, die die XML-Datei nicht verträgt.

**Comment by Marv93** [comment]
Mit regular expressions kann man hier am besten arbeiten. Bewährt hat sich bei meinen Tests:

import re

#...

erlaubtes_muster = r"[a-zA-Z]+[a-zA-Z0-9_.-]*$"
if re.match(erlaubtes_muster, config_name) == None:
    # Name ist nicht ok, Error werfen
else:
    # Name ist ok

**Comment by versus167** [comment]
Pull request integriert
